import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  // safelist: [
  //   {
  //     pattern:
  //       /bg-(error|text|navy|)|text-(sm|base|lg|xl|2xl|3xl|4xl|5xl|6xl)|(w|h)-(auto|px|[1-9]\d{0,2}|full|screen|max|min|fit)|(p|pt|pr|pb|pl|px|py)-(0|px|[1-9]\d{0,2})|(m|mt|mr|mb|ml|mx|my)-(0|px|[1-9]\d{0,2})|rounded-(sm|md|lg|xl|2xl|3xl)|shadow-(sm|md|lg|xl|2xl|inner|none)|(flex|grid|block|inline|inline-block|hidden)|/,
  //   },
  // ],
  safelist: [
    // 너비 및 높이
    "w-fit",
    "w-full",
    "w-screen",
    "w-max",
    "w-min",
    "h-fit",
    "h-full",
    "h-screen",
    "h-max",
    "h-min",
    // 텍스트 크기
    "text-sm",
    "text-base",
    "text-lg",
    "text-xl",
    "text-2xl",
    "text-3xl",
    "text-4xl",
    "text-5xl",
    "text-6xl",
    // 배경색
    "bg-error",
    "bg-navy",
    "bg-text",
    // 그림자 및 상태
    "shadow-none",
    "shadow-sm",
    "shadow-md",
    "shadow-lg",
    "shadow-xl",
    "shadow-2xl",
    "active:scale-100",
    "active:scale-90",
    "active:scale-75",
    // 테두리 반경
    "rounded-sm",
    "rounded-md",
    "rounded-lg",
    "rounded-xl",
    "rounded-2xl",
    "rounded-3xl",
    // 패딩 및 마진
    "p-0",
    "p-1",
    "p-2",
    "p-3",
    "p-4",
    "p-5",
    "p-6",
    "pt-0",
    "pt-1",
    "pt-2",
    "pt-3",
    "pt-4",
    "pt-5",
    "pt-6",
    "pr-0",
    "pr-1",
    "pr-2",
    "pr-3",
    "pr-4",
    "pr-5",
    "pr-6",
    "pb-0",
    "pb-1",
    "pb-2",
    "pb-3",
    "pb-4",
    "pb-5",
    "pb-6",
    "pl-0",
    "pl-1",
    "pl-2",
    "pl-3",
    "pl-4",
    "pl-5",
    "pl-6",
    "px-0",
    "px-1",
    "px-2",
    "px-3",
    "px-4",
    "px-5",
    "px-6",
    "py-0",
    "py-1",
    "py-2",
    "py-3",
    "py-4",
    "py-5",
    "py-6",
    "m-0",
    "m-1",
    "m-2",
    "m-3",
    "m-4",
    "m-5",
    "m-6",
    "mt-0",
    "mt-1",
    "mt-2",
    "mt-3",
    "mt-4",
    "mt-5",
    "mt-6",
    "mr-0",
    "mr-1",
    "mr-2",
    "mr-3",
    "mr-4",
    "mr-5",
    "mr-6",
    "mb-0",
    "mb-1",
    "mb-2",
    "mb-3",
    "mb-4",
    "mb-5",
    "mb-6",
    "ml-0",
    "ml-1",
    "ml-2",
    "ml-3",
    "ml-4",
    "ml-5",
    "ml-6",
    "mx-0",
    "mx-1",
    "mx-2",
    "mx-3",
    "mx-4",
    "mx-5",
    "mx-6",
    "my-0",
    "my-1",
    "my-2",
    "my-3",
    "my-4",
    "my-5",
    "my-6",
    // 디스플레이 속성
    "flex",
    "grid",
    "block",
    "inline",
    "inline-block",
    "hidden",
    // 기타
    "absolute",
    "relative",
    "fixed",
    "sticky",
    "static",
  ],
  theme: {
    extend: {
      backgroundImage: {
        "gradient-radial": "radial-gradient(var(--tw-gradient-stops))",
        "gradient-conic":
          "conic-gradient(from 180deg at 50% 50%, var(--tw-gradient-stops))",
      },
      colors: {
        main: "#0095F6",
        line: "#d8d5d5",
        navy: "#00376B",
        grey: "#fafafa",
        text: "#737373",
        error: "#ed2024",
      },
    },
  },
  plugins: [],
};
export default config;
