import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import ReactQueryProviders from "@/hooks/useReactQuery";
import NavMenu from "@/app/_component/NavMenu";
import Script from "next/script";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body className={inter.className + " flex justify-center"}>
        <ReactQueryProviders>
          <main className="flex flex-col bg-white w-full max-w-[25rem] h-screen">
            {children}
            <nav className="px-3 py-4 border-t border-gray-100">
              <ul className="flex items-center">
                <NavMenu />
              </ul>
            </nav>
          </main>
        </ReactQueryProviders>
        <Script
          src={`//dapi.kakao.com/v2/maps/sdk.js?appkey=${process.env.KAKAO_JS_APPKEY}&libraries=services,clusterer&autoload=false`}
          strategy="beforeInteractive"
        />
      </body>
    </html>
  );
}
